// <auto-generated />
using System;
using ItalianApp.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ItalianApp.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260811092105_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ItalianApp.Api.Features.Catalog.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("IconKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NameFr")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("NameIt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("ItalianApp.Api.Features.Catalog.PhoneticTip", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AdviceFr")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("LabelFr")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PhonemeSymbols")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Code");

                    b.ToTable("PhoneticTips", (string)null);
                });

            modelBuilder.Entity("ItalianApp.Api.Features.Catalog.Phrase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ContextFr")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneticTraps")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("TextFr")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("TextIt")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("TtsVoice")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId", "TextIt")
                        .IsUnique();

                    b.HasIndex("ScenarioId", "ReviewedAt", "Difficulty");

                    b.ToTable("Phrases", null, t =>
                        {
                            t.HasCheckConstraint("CK_Phrases_Difficulty", "\"Difficulty\" BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("ItalianApp.Api.Features.Catalog.Scenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("DescriptionFr")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TitleFr")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("TitleIt")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "DisplayOrder");

                    b.ToTable("Scenarios", (string)null);
                });

            modelBuilder.Entity("ItalianApp.Api.Features.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ItalianApp.Api.Features.Progress.Attempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AccuracyScore")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("CompletenessScore")
                        .HasColumnType("double precision");

                    b.Property<string>("FeedbackSource")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("FeedbackText")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<double>("FluencyScore")
                        .HasColumnType("double precision");

                    b.Property<double>("OverallScore")
                        .HasColumnType("double precision");

                    b.Property<string>("PhonemeScores")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("PhraseId")
                        .HasColumnType("uuid");

                    b.Property<double>("ProsodyScore")
                        .HasColumnType("double precision");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PhraseId");

                    b.HasIndex("UserId", "AttemptedAt");

                    b.HasIndex("UserId", "PhraseId", "AttemptedAt");

                    b.ToTable("Attempts", (string)null);
                });

            modelBuilder.Entity("ItalianApp.Api.Features.Progress.PhraseProgress", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PhraseId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<double>("BestScore")
                        .HasColumnType("double precision");

                    b.Property<double>("EaseFactor")
                        .HasColumnType("double precision");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("LastScore")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("NextReviewAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Repetitions")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "PhraseId");

                    b.HasIndex("PhraseId");

                    b.HasIndex("UserId", "LastScore");

                    b.HasIndex("UserId", "NextReviewAt");

                    b.ToTable("PhraseProgress", (string)null);
                });

            modelBuilder.Entity("ItalianApp.Api.Features.Quota.DailyUsage", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("LlmCalls")
                        .HasColumnType("integer");

                    b.Property<int>("ScoringCalls")
                        .HasColumnType("integer");

                    b.Property<int>("TtsCalls")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "Date");

                    b.HasIndex("Date");

                    b.ToTable("DailyUsage", (string)null);
                });

            modelBuilder.Entity("ItalianApp.Api.Features.Catalog.Phrase", b =>
                {
                    b.HasOne("ItalianApp.Api.Features.Catalog.Scenario", "Scenario")
                        .WithMany("Phrases")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("ItalianApp.Api.Features.Catalog.Scenario", b =>
                {
                    b.HasOne("ItalianApp.Api.Features.Catalog.Category", "Category")
                        .WithMany("Scenarios")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ItalianApp.Api.Features.Progress.Attempt", b =>
                {
                    b.HasOne("ItalianApp.Api.Features.Catalog.Phrase", "Phrase")
                        .WithMany()
                        .HasForeignKey("PhraseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItalianApp.Api.Features.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phrase");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ItalianApp.Api.Features.Progress.PhraseProgress", b =>
                {
                    b.HasOne("ItalianApp.Api.Features.Catalog.Phrase", "Phrase")
                        .WithMany()
                        .HasForeignKey("PhraseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItalianApp.Api.Features.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phrase");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ItalianApp.Api.Features.Quota.DailyUsage", b =>
                {
                    b.HasOne("ItalianApp.Api.Features.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ItalianApp.Api.Features.Catalog.Category", b =>
                {
                    b.Navigation("Scenarios");
                });

            modelBuilder.Entity("ItalianApp.Api.Features.Catalog.Scenario", b =>
                {
                    b.Navigation("Phrases");
                });
#pragma warning restore 612, 618
        }
    }
}
